### ISSUE TITLE
Create Pinned Navigation Bar for Mobile

### ISSUE THREAD

**Issue by ChristianBingman** [acm-uic/sparkhacks-2023#158]
Create the navigation for for mobile which contains links to other pages.

DoD:
- Navigation bar with logo and hamburger menu
- Clicking the hamburger menu shows a fullscreen menu of pages
- The menu animates in from the right
- The navigation bar is pinned to the top of the screen

**Comment by munnokd** [comment]
Can you assign this issue to me?
