### ISSUE TITLE
Fix Want to Attend? Text Color

### ISSUE THREAD

**Issue by ChristianBingman** [acm-uic/sparkhacks-2023#160]
The text color for Want to Attend? component is still black.

DoD:
- Text color for Want to Attend? section is white

**Comment by ChristianBingman** [comment]
Also noticed that this actually only happens on Mobile.

**Comment by Dheerajjha451** [comment]
@ChristianBingman XS is used for mobile in bootstrap, but right now when I am trying to change the code, it doesn't work, so I decided to separate the code into md and sm, which are for laptop and tablet. It is working correctly, as you can see in these screenshots. If it is correct, then please assign it to me so I can pull the request. If you want the code screenshot then tell me I will share the code screenshot here.
![mobile](https://user-images.githubusercontent.com/106474979/222155858-2622ba2f-b0d1-4ee5-a665-b1cad7318b9e.png)

![large](https://user-images.githubusercontent.com/106474979/222155523-28e44f05-053f-4a29-b0a0-8124c08a142d.png)
4979/222155492-b4cf1f1d-cdf5-4cba-ac23-fd60fc982f30.png)

**Comment by Dheerajjha451** [comment]
@ChristianBingman This section is only white on mobile.
