### ISSUE TITLE
Fix Button Not Filling Width of Screen

### ISSUE THREAD

**Issue by ChristianBingman** [acm-uic/sparkhacks-2023#161]
The RSVP and Send buttons on the Contact Us page do not extend to the full width of the screen.

DoD:
- Buttons fill the width of their containing box

**Comment by Thetechyteacher** [comment]
Hi, 

I can do this, let me know if you still need help here 👍

**Comment by Thetechyteacher** [comment]
Hi, 

i was about to make a start on this but I think someone else has done it?

**Comment by ChristianBingman** [comment]
Go ahead and work on it, I would prefer it to use tailwind instead of CSS styles, and I already assigned you to it.

**Comment by ChristianBingman** [comment]
Sorry for the removal, but this is unfortunately needed for the home page header.
