### ISSUE TITLE
Fix Want to Attend? Background Image Not Spanning Entire Screen on a Wider Display

### ISSUE THREAD

**Issue by ChristianBingman** [acm-uic/sparkhacks-2023#164]
When in a normal 16x9 aspect ratio on a larger screen, the background image does not properly scale to fill the width of the screen.
![image](https://user-images.githubusercontent.com/42191425/221391883-73ed466f-9b98-47ae-b7eb-031ef2e724d8.png)
DoD:
- The background image for Want to Attend? section fills the entire width of the screen on all screen sizes

**Comment by simonC137** [comment]
@ChristianBingman I'm happy to work on this issue if you're happy to assign it to me. First timer here.
