### ISSUE TITLE
Create Website Footer (Desktop and Mobile)

### ISSUE THREAD

**Issue by ChristianBingman** [acm-uic/sparkhacks-2023#166]
We have an extremely simple footer that needs to be added to all pages that includes links to all other pages and to our socials.

DoD:
- Simple black footer on all pages with links to socials, pages, and this Github repo for licensing
- Includes both mobile and desktop

![Home 2 part 2](https://user-images.githubusercontent.com/42191425/221392928-a9c8aa4a-8e98-4c1a-85bd-4d28e0a8fc65.png)

**Comment by iomerkoyuncu** [comment]
Hi, I can be assigned for this issue.

**Comment by Chaitu-Tatipamula** [comment]
i this done ..?
