### ISSUE TITLE
Update All Social Media Links

### ISSUE THREAD

**Issue by ChristianBingman** [acm-uic/sparkhacks-2023#210]
Update the social media links to go to the correct social media sites.

DoD:
- The following social media links on the social page and footer are updated to point to the correct pages
- LinkedIn: https://www.linkedin.com/in/sparkhacks-uic-343612269/
- Facebook: https://www.facebook.com/profile.php?id=100090984219952
- Twitter: https://twitter.com/SparkhacksAtUIC
- Instagram: https://www.instagram.com/sparkhacksuic/
- YouTube: https://www.youtube.com/channel/UC9CxYBwFup_SCKp38-CQx8Q

**Comment by Manan-Sharma-5** [comment]
Hi, I would like to try and contribute to the following issue. Is this still open.
Thanks
