### ISSUE TITLE
Create Mobile Social Bubble Layout

### ISSUE THREAD

**Issue by ChristianBingman** [acm-uic/sparkhacks-2023#83]
Create mobile social bubble layout

DoD:
- Social bubbles are stacked horizontally, and they stack from top to bottom
- The top and bottom padding are removed

Relies on #80

**Comment by ChristianBingman** [comment]
#80

**Comment by kaodik** [comment]
Hey Chris, is this a combination of the desktop and the mobile layout based off of screen width or strictly just a mobile with?

**Comment by ChristianBingman** [comment]
You should use the tailwind styling to change the layout on small sizes. https://tailwindcss.com/docs/responsive-design
